// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntregaRazor.Models
{
    public partial class Agrietados
    {
        public string Nombre { get; set; }
        public string Arma { get; set; }
        public string Buff1 { get; set; }
        public decimal Valor1 { get; set; }
        public string Buff2 { get; set; }
        public decimal? Valor2 { get; set; }
        public string Buff3 { get; set; }
        public decimal? Valor3 { get; set; }
        public string DeBuff { get; set; }
        public decimal? ValorDebuff { get; set; }
        public string Propietario { get; set; }
    }
}