// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntregaRazor.Models
{
    public partial class Animales
    {
        public string Nombre { get; set; }
        public int Vida { get; set; }
        public int Escudo { get; set; }
        public int Armadura { get; set; }
        public decimal Velocidad { get; set; }
    }
}