// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntregaRazor.Models
{
    public partial class CuerpoAcuerpo
    {
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public decimal Dmg { get; set; }
        public decimal DmgPesado { get; set; }
        public decimal Velocidad { get; set; }
        public decimal Radio { get; set; }
        public decimal Cc { get; set; }
        public decimal Cd { get; set; }
        public decimal Sc { get; set; }
        public string Faccion { get; set; }
    }
}