// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntregaRazor.Models
{
    public partial class Equipamiento
    {
        public string Tipo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    }
}