// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntregaRazor.Models
{
    public partial class Mods
    {
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Instalacion { get; set; }
        public string Aumento1 { get; set; }
        public int Valor1 { get; set; }
        public string Aumento2 { get; set; }
        public int? Valor2 { get; set; }
        public string SetMods { get; set; }
    }
}