// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntregaRazor.Models
{
    public partial class Parches
    {
        public string Parche { get; set; }
        public DateTime? Fecha { get; set; }
    }
}