// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntregaRazor.Models
{
    public partial class Planetas
    {
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Modulos { get; set; }
        public string Jefe { get; set; }
        public int NumeroPlaneta { get; set; }
    }
}