// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntregaRazor.Models
{
    public partial class Reliquias
    {
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Bronce1 { get; set; }
        public string Bronce2 { get; set; }
        public string Bronce3 { get; set; }
        public string Plata1 { get; set; }
        public string Plata2 { get; set; }
        public string Oro { get; set; }
        public decimal BronceIntacta { get; set; }
        public decimal PlataIntacta { get; set; }
        public decimal OroIntacta { get; set; }
        public decimal BronceExcepcional { get; set; }
        public decimal PlataExcepcional { get; set; }
        public decimal OroExcepcional { get; set; }
        public decimal BroncePerfecta { get; set; }
        public decimal PlataPerfecta { get; set; }
        public decimal OroPerfecta { get; set; }
        public decimal BronceRadiante { get; set; }
        public decimal PlataRadiante { get; set; }
        public decimal OroRadiante { get; set; }
    }
}