// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntregaRazor.Models
{
    public partial class Secundarias
    {
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Secundario { get; set; }
        public decimal Dmg { get; set; }
        public int Municion { get; set; }
        public int Cargador { get; set; }
        public decimal Recarga { get; set; }
        public decimal Cadencia { get; set; }
        public decimal Cc { get; set; }
        public decimal Cd { get; set; }
        public decimal Sc { get; set; }
        public decimal Ms { get; set; }
        public string Faccion { get; set; }
    }
}