// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntregaRazor.Models
{
    public class Warframes
    {
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public int Vida { get; set; }
        public int Escudo { get; set; }
        public int Armadura { get; set; }
        public int Energia { get; set; }
        public decimal Velocidad { get; set; }
        public string Elemento { get; set; }

        //public Warframes(string nombre, string genero, int vida, int escudo, int armadura, int energia, decimal velocidad, string elemento)
        //{
        //    Nombre = nombre;
        //    Genero = genero;
        //    Vida = vida;
        //    Escudo = escudo;
        //    Armadura = armadura;
        //    Energia = energia;
        //    Velocidad = velocidad;
        //    Elemento = elemento;
        //}
    }
}